### ISSUE TITLE
Provider crash in terraform refresh command 

### ISSUE THREAD

**Issue by SoibamRepo** [HewlettPackard/terraform-provider-oneview#390]
Hi all, 

I have one scenario - I have created one server profile through terraform TF config file.  On next step, manually from Oneview, I have updated attribute like disable virtualization/NIC settings in BIOS settings. How would I sync updated BIOS settings in oneview to terraform state ? I tried with the command "terraform refresh" .. the provider crash.

Environment:

Oneview 6.20
HPE Proliant DL360 Gen 10 
Clone master branch and build terraform-oneview provider locally

Regards
Soibam

**Comment by AsisBagga** [comment]
Hi @SoibamRepo
Thank you for pointing this out. 
I have tried it, and, so far, it did not crashes. However, there was a bug in read method for bios_option, which is fixed as of now. 
Would you please share the trace logs and crash logs while it crashes. Ill have a further look into this.

**Comment by SoibamRepo** [comment]
@AsisBagga  With latest codes, I don't find provider crash. But "terraform refresh" command still does not update terraform state file with bios option.  Here are steps I follow

1. Create a Server Profile without enabling BIOS options.
2. Manually enable BIOS option in SP and update some attributes like virtualization, time zone, C-state etc .
3. Now run the command "terraform refresh" successfully 

Expected: terraform state shall be updated with latest bios options

**Comment by AsisBagga** [comment]
@SoibamRepo Thank you for responding. So when I was testing this scenario I also didn't found terraform crashing as such. However, there was an issue that the terraform was not reading bios correctly and was unable to detect the drift. 
This is now fixed and merged with the master. You may build the binary from our master branch, and for now, I'll be closing this issue. For any further queries or other issues feel free to open a new issue. Good day.
